### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#13]
Hi,

When using the Data Loader, I get the error:

> Cannot read property 'length' of undefined

I will email a copy of the sheet I am using in case you can spot anything erroneous.

All of the collection metadata is in one tab, one row per collection. Each collection has its own tab, named **C46 Recording metadata**, for example.

**Edit:** There was an "Acquisition Source" field in the sample metadata, which wasn't in the blank template. I added this to the metadata.xlsx but this didn't resolve the issue. This field should not be included on the catalogue anyway - I should have removed this from the sample metadata.

**Comment by marcolarosa** [comment]
This was a bug triggered by your sheet and not the version I was using though I don't know why b/c the data looked the same. Anyway, I've rewritten the relevant code snippet and the issue is resolved.
