### ISSUE TITLE
Fields not showing on cataloguing

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#15]
**Collection level**

- Reference
- Documentation
- Keyword
- Web address of original archive/location
- Additional information [PDF]

**Recording level**

- Language name showing as "N/A" despite field being populated
- Web address...
- Playback mode also showing as "N/A" despite field being populated

**Comment by marcolarosa** [comment]
Collection level metadata updated and will now show. Additional information was actually a link to more info. It now shows as another field.

Re the item level. Language name and playback mode we're written in the code as "Language Name" and "Playback Mode". Typo on my part b/c some headings have all words capitalised and some don't. 

Web address not in C80 but in C62. 

Re: these last two points. Please try to be consistent. It feels like you're adding things on the fly and that's how errors will be introduced. The new version i release will have this data.
