### ISSUE TITLE
Cultural advice notice

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#16]
The cultural advice notice on the website is currently:

> Cultural advice notice
Torres Strait Islander peoples should be aware that this website contains images, voices and names of deceased persons.

> This website may include collection materials, or descriptions of collection materials, that are secret, sacred or sensitive, or have traditional protocols around who can access them. All users are warned that this website and linked resources include words and descriptions which may be outdated and culturally sensitive. Terms that reflect the author’s attitude or that of the period in which the item was written may be considered inappropriate or offensive today.

Please can the notice on the Raspberry Pi (part of the language selector) be updated to the above text?

**Comment by marcolarosa** [comment]
Easily changed but then the Tok Pisin translation won't match. Is that an issue? If so - you need to reach out to Steven I guess to get this text translated.

**Comment by rebekahhayes** [comment]
Thanks, I will contact Steven to ask for an updated translation and forward ASAP.

**Comment by rebekahhayes** [comment]
Thanks for updating this! Please could the first line be removed for the Tok Pisin instance?
