### ISSUE TITLE
British Museum logo

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#17]
The British Museum logo looks squashed on my iPhone screen. Do you know if this a device-specific issue or whether the proportions need adjusting?

**Comment by marcolarosa** [comment]
I'm not seeing it:

![Screen Shot 2021-03-30 at 6 34 25 pm](https://user-images.githubusercontent.com/2639995/112950988-9e280480-9186-11eb-98bd-6a5521c986f2.png)

**Comment by rebekahhayes** [comment]
I've attached a screenshot from my browser using the Inspect tool. It looks fine on all on all of the other pre-set screen sizes apart from iPhone 5/SE. Can this be resolved e.g. keeping the image in proportion regardless of screen size?

![image](https://user-images.githubusercontent.com/35967074/113020116-2eac1800-917a-11eb-8d44-7fb0a1fa39c8.png)

**Comment by marcolarosa** [comment]
Fixed in 07edc5a65b54635ab2c26419256398ae6f5215ca
