### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#22]
I'm testing with Solomon Islands metadata; three collections in one sheet.

I'm receiving this error message on the Data Loader:

> Cannot read property 'replace' of undefined

It's only occurring when I add metadata from the C108 collection. The metadata for this C108 collection has been added to the sheet in the same way as the other two Solomon Islands collections,. I've checked the sheet and there aren't any obvious errors/differences. All data files are accounted for.

Do you know what could be causing the issue?

**Comment by marcolarosa** [comment]
I will need your sheet.

**Comment by rebekahhayes** [comment]
I've tested with similar Solomon Islands metadata and no longer receiving this error.
