### ISSUE TITLE
IPNGS partner page - Tok Pisin

### ISSUE THREAD

**Issue by rebekahhayes** [CoEDL/BritishLibrary-DataLoader#5]
The Tok Pisin translation of the IPNGS partner page needs to be updated. Two paragraphs are repeated and the third paragraph from Steven's translation is missing.

**Comment by marcolarosa** [comment]
Done

**Comment by rebekahhayes** [comment]
Hi, I can't see that this has been changed on the updated version? The English version of the page also has the duplicated and missing text.

**Comment by marcolarosa** [comment]
Sorry - the text was updated but the app was including the second blob twice.
